//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayap_SalonPhenomenon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masters()
        {
            this.Registrations = new HashSet<Registrations>();
        }
    
        public int IDMaster { get; set; }
        public string MasterName { get; set; }
        public string MasterSurname { get; set; }
        public string MasterPatronymic { get; set; }
        public string MasterPhoneNumber { get; set; }
        public string MasterSpecialization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registrations> Registrations { get; set; }
    }
}
