//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayap_SalonPhenomenon.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonEntities : DbContext
    {
        private static SalonEntities _context;

        public static SalonEntities GetContext()
        {
            if (_context == null)
                _context = new SalonEntities();
            return _context;
        }
        public SalonEntities()
            : base("name=SalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<Registrations> Registrations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Salon> Salon { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
