//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayap_SalonPhenomenon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        public int IDRegistration { get; set; }
        public System.DateTime DateRegistration { get; set; }
        public int ClientID { get; set; }
        public int ServiceID { get; set; }
        public int MasterID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Masters Masters { get; set; }
        public virtual Services Services { get; set; }
    }
}
