//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayap_SalonPhenomenon.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int IDRole { get; set; }
        public string NameRole { get; set; }
    }
}
